package app.persistence.entities.domain;

import app.persistence.entities.IEntity;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.time.LocalDateTime;
import java.util.Objects;

@Getter
@Setter
@NoArgsConstructor
@ToString
@Entity
public class Campaign implements IEntity
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter(AccessLevel.NONE)
    @EqualsAndHashCode.Include
    private Long id;

    // private User gameMaster;

    // @Column(unique = true)
    // private List<CharacterSheet> players;
    // private Map<String, String> gameMasterNotes; // TODO Maybe another Key?
    // private Map<String, String> sessionLogs; // TODO Maybe another Key?

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    // public Campaign(User gameMaster) { this.gameMaster = gameMaster; }

    @PrePersist
    protected void onCreate()
    {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate()
    {
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Replaces Lombok's @EqualsAndHashCode, which is unsafe with JPA due to Hibernate proxy behavior.
     * Generated by IntelliJ to handle equality correctly for both managed entities and lazy-loaded proxies.
     */

    @Override
    public final boolean equals(Object object)
    {
        if (this == object) return true;
        if (object == null) return false;
        Class<?> oEffectiveClass = object instanceof HibernateProxy ? ((HibernateProxy) object).getHibernateLazyInitializer().getPersistentClass() : object.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass) return false;
        Campaign campaign = (Campaign) object;
        return getId() != null && Objects.equals(getId(), campaign.getId());
    }

    @Override
    public final int hashCode()
    {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }
}
