package app.persistence.entities.domain;

import app.enums.CampaignRole;
import app.persistence.entities.IEntity;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.util.Objects;

@Getter
@Setter
@ToString
@Entity
@Table(uniqueConstraints = @UniqueConstraint(name = "uk_user_membership_campaign", columnNames = {"user_id", "campaign_id"}))
public class CampaignMembership implements IEntity
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter(AccessLevel.NONE)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "campaign_id", nullable = false)
    private Campaign campaign;

    @OneToOne(optional = true)
    @JoinColumn(name = "character_sheet_id", unique = true)
    private CharacterSheet characterSheet;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private CampaignRole role;

    /**
     * Replaces Lombok's @EqualsAndHashCode, which is unsafe with JPA due to Hibernate proxy behavior.
     * Generated by IntelliJ to handle equality correctly for both managed entities and lazy-loaded proxies.
     */

    @Override
    public final boolean equals(Object object)
    {
        if (this == object) return true;
        if (object == null) return false;
        Class<?> oEffectiveClass = object instanceof HibernateProxy ? ((HibernateProxy) object).getHibernateLazyInitializer().getPersistentClass() : object.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass) return false;
        CampaignMembership that = (CampaignMembership) object;
        return getId() != null && Objects.equals(getId(), that.getId());
    }

    @Override
    public final int hashCode()
    {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }
}
