package app.persistence.entities.domain;

import app.enums.Ability;
import app.persistence.entities.IEntity;
import app.persistence.entities.reference.Language;
import app.persistence.entities.reference.Race;
import app.persistence.entities.reference.Subrace;
import app.utils.Validator;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

@Getter
@Setter
@NoArgsConstructor
@ToString
@Entity
@Table(name = "character_sheet", uniqueConstraints = @UniqueConstraint(name = "uk_user_character_name", columnNames = {"user_id", "name"}))
public class CharacterSheet implements IEntity
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter(AccessLevel.NONE)
    private Long id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Column(nullable = false)
    private String name;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "race_id")
    private Race race;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "subrace_id")
    private Subrace subrace;

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
            name = "character_languages",
            joinColumns = @JoinColumn(name = "character_id"),
            inverseJoinColumns = @JoinColumn(name = "language_id")
    )
    private Set<Language> languages;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(
            name = "character_ability_scores",
            joinColumns = @JoinColumn(name = "character_id")
    )
    @MapKeyColumn(name = "ability")
    @MapKeyEnumerated(EnumType.STRING)
    @Column(name = "score")
    private Map<Ability, Integer> abilityScores;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(
            name = "character_notes",
            joinColumns = @JoinColumn(name = "character_id")
    )
    @MapKeyColumn(name = "title")
    @Column(name = "note", columnDefinition = "TEXT")
    private Map<String, String> notes; // TODO Eligible for refactor: Create separate Note entity with timestamps, ordering, and per-note access control

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public CharacterSheet(User user, String name, Race race, Subrace subrace, Set<Language> languages, Map<Ability, Integer> abilityScores)
    {
        this.user = user;
        this.name = name;
        this.race = race;
        this.subrace = subrace;
        this.languages = languages;
        this.abilityScores = abilityScores;
    }

    @PrePersist
    protected void onCreate()
    {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
        this.name = normalizeName(this.name);
    }

    @PreUpdate
    protected void onUpdate()
    {
        this.updatedAt = LocalDateTime.now();
        this.name = normalizeName(this.name);
    }

    private String normalizeName(String name)
    {
        Validator.notNullOrBlank(name);
        return name.trim();
    }

    /**
     * Replaces Lombok's @EqualsAndHashCode, which is unsafe with JPA due to Hibernate proxy behavior.
     * Generated by IntelliJ to handle equality correctly for both managed entities and lazy-loaded proxies.
     */

    @Override
    public final boolean equals(Object object)
    {
        if (this == object) return true;
        if (object == null) return false;
        Class<?> oEffectiveClass = object instanceof HibernateProxy ? ((HibernateProxy) object).getHibernateLazyInitializer().getPersistentClass() : object.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass) return false;
        CharacterSheet that = (CharacterSheet) object;
        return getId() != null && Objects.equals(getId(), that.getId());
    }

    @Override
    public final int hashCode()
    {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }
}