package app.persistence.entities.domain;

import app.persistence.entities.IEntity;
import app.security.enums.Role;
import app.utils.Validator;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.proxy.HibernateProxy;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

@Getter
@Setter
@NoArgsConstructor
@ToString
@Entity
@Table(name = "users")
public class User implements IEntity
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Setter(AccessLevel.NONE)
    private Long id;

    @Column(nullable = false, unique = true)
    private String email;

    @Column(nullable = false, unique = true)
    private String username;

    @Column(name = "hashed_password", nullable = false, unique = false, length = 60)
    private String hashedPassword;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "role")
    @Enumerated(EnumType.STRING)
    private Set<Role> roles = new HashSet<>(Set.of(Role.USER));

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public User(String email, String username, String hashedPassword)
    {
        this.email = email;
        this.username = username;
        this.hashedPassword = hashedPassword;
    }

    @PrePersist
    protected void onCreate()
    {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
        this.email = this.email.toLowerCase().trim();
        this.username = normalizeName(this.username);
    }

    @PreUpdate
    protected void onUpdate()
    {
        this.updatedAt = LocalDateTime.now();
        this.email = this.email.toLowerCase().trim();
        this.username = normalizeName(this.username);
    }

    public boolean addRole(Role role)
    {
        if (roles.contains(role))
        {
            return false;
        }
        roles.add(role);
        return true;
    }

    public boolean removeRole(Role role)
    {
        if (!roles.contains(role))
        {
            return false;
        }
        roles.remove(role);
        return true;
    }

    private String normalizeName(String name)
    {
        Validator.notNullOrBlank(name);
        return name.trim();
    }

    /**
     * Replaces Lombok's @EqualsAndHashCode, which is unsafe with JPA due to Hibernate proxy behavior.
     * Generated by IntelliJ to handle equality correctly for both managed entities and lazy-loaded proxies.
     */

    @Override
    public final boolean equals(Object object)
    {
        if (this == object) return true;
        if (object == null) return false;
        Class<?> oEffectiveClass = object instanceof HibernateProxy ? ((HibernateProxy) object).getHibernateLazyInitializer().getPersistentClass() : object.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass) return false;
        User user = (User) object;
        return getId() != null && Objects.equals(getId(), user.getId());
    }

    @Override
    public final int hashCode()
    {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }
}


