@baseURL = https://www.dnd5eapi.co/api/2014

### GET all resource URLs
GET {{baseURL}}

### GET all races
GET {{baseURL}}/races

### GET race details (example HUMAN)
GET {{baseURL}}/races/human

### GET race details (example ELF - has subrace)
GET {{baseURL}}/races/elf

### GET all classes
GET {{baseURL}}/classes

### GET class details (example WIZARD)
GET {{baseURL}}/classes/wizard

### GET class details (example FIGHTER)
GET {{baseURL}}/classes/wizard

### GET ability bonus details (example STRENGTH)
GET {{baseURL}}/ability-scores/str