### Register user
POST {{url}}/auth/register
Content-Type: application/json

{
  "email": "john@admin.com",
  "username": "John-Admin",
  "password": "P4sswo8d?"
}

### Login
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "john@admin.com",
  "password": "P4sswo8d?"
}